In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("Customers.csv")
dataset

CustomerID  Gender  Age  Annual Income ($)  Spending Score (1-100)   
0              1    Male   19              15000                      39  \
1              2    Male   21              35000                      81   
2              3  Female   20              86000                       6   
3              4  Female   23              59000                      77   
4              5  Female   31              38000                      40   
...          ...     ...  ...                ...                     ...   
1995        1996  Female   71             184387                      40   
1996        1997  Female   91              73158                      32   
1997        1998    Male   87              90961                      14   
1998        1999    Male   77             182109                       4   
1999        2000    Male   90             110610                      52   

         Profession  Work Experience  Family Size  
0        Healthcare                1            4  
1          Engineer                3            3  
2          Engineer                1            1  
3            Lawyer                0            2  
4     Entertainment                2            6  
...             ...              ...          ...  
1995         Artist                8            7  
1996         Doctor                7            7  
1997     Healthcare                9            2  
1998      Executive                7            2  
1999  Entertainment                5            2  

[2000 rows x 8 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder as Le
dataset["Gender"] = Le.fit_transform(dataset["Gender"])
dataset


TypeError: LabelEncoder.fit_transform() missing 1 required positional argument: 'X'

In [4]:

x = dataset.iloc[:, [1,2,3]].values
y = dataset.iloc[:, 4].values
     

In [5]:
x

array([['Male', 19, 15000],
       ['Male', 21, 35000],
       ['Female', 20, 86000],
       ...,
       ['Male', 87, 90961],
       ['Male', 77, 182109],
       ['Male', 90, 110610]], dtype=object)

In [6]:
y

array([39, 81,  6, ..., 14,  4, 52], dtype=int64)

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.75, random_state=0)

In [8]:
x_train

array([['Male', 9, 165194],
       ['Male', 22, 162598],
       ['Male', 43, 89000],
       ...,
       ['Female', 52, 133214],
       ['Male', 0, 151298],
       ['Female', 54, 145679]], dtype=object)

In [9]:
x_test

array([['Female', 65, 119889],
       ['Male', 97, 142214],
       ['Female', 84, 133765],
       ...,
       ['Female', 38, 71000],
       ['Male', 65, 134213],
       ['Male', 74, 164976]], dtype=object)

In [10]:
y_train

array([10, 84, 35, 48, 98, 16, 64, 77, 86, 87, 73, 67, 66, 94, 21, 23, 39,
       82,  4, 97, 41, 37, 36, 38, 51, 84, 76, 61, 26, 60, 36, 44, 87, 51,
       49,  1, 35, 52, 12,  6, 21, 10, 73, 83, 37, 36, 65, 65, 84,  9, 56,
       37, 93, 75, 46, 42, 67, 42, 21, 50, 80, 23, 83, 54, 71, 17, 14, 93,
       94, 24, 98, 65, 48, 18, 60, 60, 75,  3, 82, 39, 85, 38, 20, 11, 13,
       97,  1, 61, 15, 31, 77, 88, 71, 27, 39,  3, 43, 92, 46, 25, 50, 63,
       86, 86, 49, 34, 24,  7, 82, 98, 47, 99, 85, 74, 35, 14,  3, 16, 34,
       36, 20, 76, 44, 12, 27, 47, 72, 26, 50, 80, 43, 74, 59, 46,  2, 71,
        3,  4, 40, 58, 40, 57, 62, 85, 61, 22, 40, 98, 76, 88, 34, 80, 45,
       45, 70, 81, 78, 65, 63, 78, 88, 47,  1, 47, 99, 51, 82, 36, 28, 99,
       49, 32, 63, 53, 92, 15, 92, 27, 99, 95, 37, 43, 46, 75, 85,  7, 78,
       27, 70, 89, 74, 62, 88, 17, 22, 88, 33, 92, 25, 17, 12, 49, 82, 15,
       27, 83, 24, 58, 90, 42, 37, 69, 65, 41, 56, 27, 84, 85, 62, 40, 52,
       72, 18, 34, 28, 37

In [11]:
y_test

array([11, 32, 83, ..., 42, 32, 89], dtype=int64)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
     

ValueError: could not convert string to float: 'Male'